### PR TITLE
Add tags and meta to the models tables

### PR DESCRIPTION
**Pull request by ahmedrad**
## Description:
Adds the tags and meta fields to the models table and bubbles them up to the dim table

### CODE REVIEW

**Comment by ma1ster** [comment]
thanks, I'd love to see those 2 fields as well

**Comment by ahmedrad** [comment]
@NiallRees Would you or anyone from brooklyn-data be able to review this soon?

**Comment by jaypeedevlin** [comment]
@ahmedrad jumping in for Niall here who has been away for the last few days — I think we're generally in favor of merging this PR, but what has held us back is internal conversations about how to handle schema changes more generally in the package.

By way of explanation, for folks running 1.x and upgrading to a version with this PR they would need some code to be run to add the columns to the source table in order to be able to write into them.  We're considering reworking the table creation steps to avoid managing a complex set of schema migrations not just here, but over time as we continue to add/improve things.

I appreciate your patience while we navigate a way forward here.

**Comment by ahmedrad** [comment]
> @ahmedrad jumping in for Niall here who has been away for the last few days — I think we're generally in favor of merging this PR, but what has held us back is internal conversations about how to handle schema changes more generally in the package.
> 
> By way of explanation, for folks running 1.x and upgrading to a version with this PR they would need some code to be run to add the columns to the source table in order to be able to write into them. We're considering reworking the table creation steps to avoid managing a complex set of schema migrations not just here, but over time as we continue to add/improve things.
> 
> I appreciate your patience while we navigate a way forward here.

@jaypeedevlin just to add our 2 cents as new users to this package. For us, we use star schema modelling but there's still quite a few differences between our warehouse and the models provided by the package and so we decided to do our own modelling so we can stay consistent across the warehouse. I'm not sure that's something you'd ever be able to get away from. For example using `TIMESTAMP_NTZ` vs `TIMESTAMP_TZ` types, prefix vs suffix naming `dim_` vs `_dim`, shortened naming vs not `fct_` vs `fact_`, column naming conventions etc...

it would be pretty difficult to provide high level models that would immediately mesh with any existing data warehouse without any manipulation. I would much rather have access to the entire json blob of high level objects so that I can model however I want to for my needs. For example if I consider dbt to be broken into `sources, models, tests, macros, exposures and metrics` then for every run I'd want to have a table for each that contains the raw json blob of the object with some associated metadata about the run it was developed in.

That way we'll have all the flexibility we need in extracting and modelling the json objects however we need to and in a way that matches the rest of the warehouse without having to deal with most of the manifest structure. The blobs of the specific objects may change often and we'll have to deal with that but the main objects that dbt consists off shouldn't change all that often even with manifest schema changes and so it'll spare you having to re-work your tables often.

and I'd rather get access to your tables as sources when I install the package, because that's what they essentially are, a source for dbt run data that still needs to be staged and modelled in our warehouse according to our conventions

**Comment by jaypeedevlin** [comment]
@ahmedrad PR 188 is now merged which unblocks this PR.  My suggestion to you would be to close and reopen a fresh branch against this, since so much was changed in that PR, but up to you.  I'm going to open a separate issue for the rest of your comment since it's not directly relevant to this PR.

**Comment by bchoifigma** [comment]
this would be super useful! any idea when this could be merged in?

**Comment by NiallRees** [comment]
Hey @ahmedrad - really excited to get this in, do you think you’ll be able to get this rebased?

**Comment by ahmedrad** [comment]
yup should be able to over the coming week!

**Comment by ahmedrad** [comment]
hey @NiallRees I opened a new PR all together over here: [212](https://github.com/brooklyn-data/dbt_artifacts/pull/212)

**Pull request closed without merging**
