### PR TITLE
TEST BQ Invocations

### PR DESCRIPTION
**Pull request by glsdown**
## Overview

This PR is to try and debug why BQ is failing on CI but not locally.

## Update type - breaking / non-breaking

- [ ] Minor bug fix
- [ ] Documentation improvements
- [ ] Quality of Life improvements
- [ ] New features (non-breaking change)
- [ ] New features (breaking change)
- [ ] Other (non-breaking change)
- [ ] Other (breaking change)

## What databases have you tested with?

- [ ] Snowflake
- [ ] Google BigQuery
- [ ] Databricks
- [ ] Spark
- [ ] N/A

### CODE REVIEW

**Comment by d-cole** [comment]
Could be related to [this issue](https://github.com/brooklyn-data/dbt_artifacts/issues/337) and [PR](https://github.com/brooklyn-data/dbt_artifacts/pull/327). I'm encountering this error when attempting to add dbt_artifacts to an existing project using dbt-bigquery 1.5.0.

**Comment by glsdown** [comment]
Thanks @d-cole . The fix for that issue should be in here already (from #326), but for whatever reason it's failing in the action only. The PR you have linked looks to be a duplicate of that :) Running locally works as intended, which is why (unfortunately) I've had to open a PR to run it and work out why the action is just failing in GH.

**Comment by d-cole** [comment]
> Thanks @d-cole . The fix for that issue should be in here already (from #326), but for whatever reason it's failing in the action only. The PR you have linked looks to be a duplicate of that :)

Okay great, I'll close the duplicate PR and issue. Thank you!

**Comment by glsdown** [comment]
Closing as the issue has now been identified by @jared-rimmer 🎉

**Pull request closed without merging**
