### PR TITLE
Adding support for dbt v1.6

### PR DESCRIPTION
**Pull request by sfc-gh-kumaurya**
## Overview
Adds support to dbt version 1.6, updated workflows to run on dbt-snowflake plugin v1.6.0 and dbt version 1.6.0

## Update type - non-breaking

- [ ] Minor bug fix
- [x] Quality of Life improvements
- [x] New features (non-breaking change)

## What does this solve?
Supports dbt latest version v1.6.0
issue: https://github.com/brooklyn-data/dbt_artifacts/issues/373 

## What databases have you tested with?

- [x] Snowflake

### CODE REVIEW

**Comment by sfc-gh-kumaurya** [comment]
@glsdown is this the right way to make a PR into dbt_artifacts and if so, could you take a look pls?

**Comment by chancekbarkley** [comment]
Is there a timeline on merging this PR?

**Comment by the-davidsn** [comment]
Push! Would be awesome having support for dbt v.1.6

**Comment by piotrs-ae** [comment]
+1 from me!

**Comment by katepaydhealth** [comment]
Looking forward to having supports for dbt v.1.6

**Comment by zhai-chris** [comment]
Yes please.  Looking forward to have artifacts working for DBT 1.6.

**Comment by SarahAyaz** [comment]
Looking forward to having support for dbt v1.6

**Comment by charles-astrafy** [comment]
+1 here as well

**Comment by Micatio** [comment]
PR looks good to me. @NiallRees can we merge please?

**Review by Micatio — APPROVED** [review]
version changes look fine

**Comment by NiallRees** [comment]
> PR looks good to me. @NiallRees can we merge please?

I wish I could, I’m no longer with Brooklyn Data though. I’ll reach out to someone who can and ask them to take a look.

**Comment by sfc-gh-kumaurya** [comment]
> > PR looks good to me. @NiallRees can we merge please?
> 
> I wish I could, I’m no longer with Brooklyn Data though. I’ll reach out to someone who can and ask them to take a look.

Thank you @NiallRees, that would be very helpful.

**Comment by piotrs-ae** [comment]
Hi there, is there any possibility to get a merge soon?

**Comment by chancekbarkley** [comment]
Is this project dead?

**Review by glsdown — APPROVED** [review]

**Pull request merged**
