### PR TITLE
Add rows_affected column for snowflake

### PR DESCRIPTION
**Pull request by iribarnesy**
Reference the issue #196 

[x] model_executions
[x] seed_executions
[x] snapshot_executions

### CODE REVIEW

**Review by NiallRees — APPROVED** [review]

**Comment by NiallRees** [comment]
Thank you @iribarnesy !

**Comment by bhratkapoor** [comment]
Hi @iribarnesy, I have used the latest code for upload_model_executions.sql file, now rows_affected column value is reflecting but its always inserting 1.

Sample Model used :
{{ config(
  materialized='table',
  database='Test',
  schema='temp_schema',
  alias='testing1'
) }}

select * from "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."CUSTOMER" where C_Nationkey=13

MODEL_EXECUTIONS table is getting populated with 1 as  rows_affected column

**Comment by iribarnesy** [comment]
> Hi @iribarnesy, I have used the latest code for upload_model_executions.sql file, now rows_affected column value is reflecting but its always inserting 1.
> 
> Sample Model used : {{ config( materialized='table', database='Test', schema='temp_schema', alias='testing1' ) }}
> 
> select * from "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."CUSTOMER" where C_Nationkey=13
> 
> MODEL_EXECUTIONS table is getting populated with 1 as rows_affected column

As I investigated before pushing that piece of code, I thought that the first run of any model will always return 1 for the number of rows_affected. I don't know if the source of this behavior is dbt-snowflake or snowflake.

**Comment by NiallRees** [comment]
Could you try using dbt-snowflake==1.2.0? This behaviour should have been fixed as part of https://github.com/dbt-labs/dbt-snowflake/pull/153.

**Comment by bhratkapoor** [comment]
I am using 1.2.1 version and getting always 1 in row_affected column

On model.my_new_project.test1: /* {"app": "dbt", "dbt_version": "1.2.1", "profile_name": "user", "target_name": "default", "node_id": "model.my_new_project.test1"} */
create or replace transient table Test.temp_schema.testing1  as
      (

select * from "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."CUSTOMER" where C_Nationkey=13
      );

**Comment by NiallRees** [comment]
You'll only see values greater other than 1 for incremental models which are running incrementally (not a full refresh), which it doesn't look like your example is. Snowflake only reports row counts for insert and merge into statements. Would you be able to try it with an incremental model and report back?

**Comment by bhratkapoor** [comment]
Great, I changes the materialized='incremental'. Now its capturing the affected rows. Thanks you!

**Pull request merged**
