### PR TITLE
[FIX] Fix invocations for v1.5

### PR DESCRIPTION
**Pull request by glsdown**
## Overview

Hopefully a final fix for the invocations issue in v1.5. This adds back in missing fields and fixes the issue with the fromyaml for the vars argument.

Helpful links include:
- [Docs on Warn Error Options](https://docs.getdbt.com/reference/global-configs#warnings-as-errors)
- [IncludeExclude Object in source code](https://github.com/dbt-labs/dbt-core/blob/1fdebc660b8900a7ff03d2dce9830b1d51725734/core/dbt/helper_types.py#L93)

## Update type - breaking / non-breaking

- [x] Minor bug fix
- [ ] Documentation improvements
- [ ] Quality of Life improvements
- [ ] New features (non-breaking change)
- [ ] New features (breaking change)
- [ ] Other (non-breaking change)
- [ ] Other (breaking change)

## What does this solve?

- #337 
-  #307 
- #296

## Outstanding questions

None

## What databases have you tested with?

- [x] Snowflake
- [x] Google BigQuery
- [ ] Databricks
- [ ] Spark
- [ ] N/A

### CODE REVIEW

**Review by jared-rimmer — APPROVED** [review]

**Comment by rrchorly** [comment]
Hi @glsdown has this fix gone into version 2.3.0? I just tried installing and running with 2.3 but am still getting the _Object of type WarnErrorOptions is not JSON serializable_ error.

**Comment by jared-rimmer** [comment]
> Hi @glsdown has this fix gone into version 2.3.0? I just tried installing and running with 2.3 but am still getting the _Object of type WarnErrorOptions is not JSON serializable_ error.

Hi @rrchorly! Thanks for the comment. This will be in the next release!

**Comment by rrchorly** [comment]
Thanks @jared-rimmer could I also ask when the next release is scheduled for. I have a customer very keen on this fix.

**Comment by jared-rimmer** [comment]
> Thanks @jared-rimmer could I also ask when the next release is scheduled for. I have a customer very keen on this fix.

Hi @rrchorly the 2.4.0 release was done about 30 minutes ago 👍

**Comment by rrchorly** [comment]
Thanks @jared-rimmer I tested with 2.4.0 and its all good!

**Pull request merged**
