### PR TITLE
Add postgres support

### PR DESCRIPTION
**Pull request by dpguthrie**
## Overview

- Adds relevant macros to enable support for Postgres
- Adds a postgres service to the github action used for integration testing
- Aliased the subquery used in the singular test as it's necessary within Postgres (should work across all other supported DWs)

## Update type - breaking / non-breaking

- [ ] Minor bug fix
- [ ] Documentation improvements
- [ ] Quality of Life improvements
- [x] New features (non-breaking change)
- [ ] New features (breaking change)
- [ ] Other (non-breaking change)
- [ ] Other (breaking change)

## What does this solve?

Support for a new platform, Postgres

## What databases have you tested with?

- [ ] Snowflake
- [ ] Google BigQuery
- [ ] Databricks
- [ ] Spark
- [x] Postgres
- [ ] N/A

### CODE REVIEW

**Comment by dpguthrie** [comment]
Passing postgres integration tests - https://github.com/dpguthrie/dbt_artifacts/actions/runs/5538393942

**Comment by glsdown** [comment]
Hi @dpguthrie . Thanks for taking the time to add this functionality in.

One of the team will spend some time reviewing it and get back to you.

**Comment by drewblinn** [comment]
Would love to see this in the next release!

**Review by glsdown — APPROVED** [review]
Thank you for your work on this. Sorry it's taken a while to review - there have been a number of changes to improve the backend, so I wanted to make sure those had been made first.

**Pull request merged**
